# Generated by Django 4.1.2 on 2022-11-27 03:29

import core.upload_to
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-created_on']},
        ),
    ]
