# Generated by Django 4.1.2 on 2022-11-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['created_on']},
        ),
    ]
