# Generated by Django 4.1.2 on 2022-11-26 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_options_alter_postcomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-created_on']},
        ),
    ]
