# Generated by Django 4.1.2 on 2022-11-28 09:31

import core.upload_to
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_options_alter_postcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=core.upload_to.user_directory_path, validators=[core.validators.validate_file_size]),
        ),
    ]
