# Generated by Django 4.1.2 on 2022-11-27 03:29

import core.upload_to
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='creative',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='award',
            name='created_on',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_on',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creative',
            name='created_on',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creative',
            name='image',
            field=models.ImageField(
                blank=True, default=None, upload_to=core.upload_to.user_directory_path),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='created_on',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Employee', 'Employee'), ('Job Seeker', 'Job Seeker'), ('Open To Collaborate', 'Open To Collaborate'), (
                'Hands Full', 'Hands Full'), ('Traveling', 'Traveling'), ('Not Specified', 'Not Specified')], default='Not Specified', max_length=19),
        ),
    ]
