# Generated by Django 4.1.2 on 2022-11-17 20:44

import core.upload_to
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.upload_to.user_directory_path),
        ),
    ]
