# Generated by Django 4.1.2 on 2022-11-21 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_creative_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='creative',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='award',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creative',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
