# Generated by Django 4.1.2 on 2022-11-27 16:21

import core.upload_to
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_award_options_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default=None, upload_to=core.upload_to.user_directory_path, validators=[core.validators.validate_file_size, django.core.validators.validate_image_file_extension]),
        ),
    ]
