# Generated by Django 4.1.2 on 2022-11-28 09:31

import core.upload_to
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=core.upload_to.user_directory_path, validators=[core.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=core.upload_to.user_directory_path, validators=[core.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='creative',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=core.upload_to.user_directory_path, validators=[core.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=core.upload_to.user_directory_path, validators=[core.validators.validate_file_size]),
        ),
    ]
