# Generated by Django 4.1.2 on 2022-11-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_award_options_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='creative',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[(None, 'Not Specified'), ('Owner', 'Owner'), ('Employee', 'Employee'), ('Job Seeker', 'Job Seeker'), ('Open To Collaborate', 'Open To Collaborate'), ('Hands Full', 'Hands Full'), ('Traveling', 'Traveling'), ('Not Specified', 'Not Specified')], default='Not Specified', max_length=19, null=True),
        ),
    ]
