# Generated by Django 4.1.2 on 2022-11-28 17:53

import core.upload_to
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_award_image_alter_certificate_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=core.upload_to.user_directory_path, validators=[core.validators.validate_file_size]),
        ),
    ]
