# Generated by Django 4.1.2 on 2022-11-26 23:08

import core.upload_to
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_award_slug_alter_certificate_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=core.upload_to.user_directory_path),
        ),
    ]
