# Generated by Django 4.1.2 on 2022-11-26 23:16

import core.upload_to
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.upload_to.user_directory_path),
        ),
    ]
