
services: 
  - type: web
    name: cotal-api
    env: python
    region: Frankfurt
    buildCommand: "./build.sh"
    startCommand: gunicorn cotal_drf_api.wsgi:application
    repo: https://github.com/MTraveller/cotal-drf.git
    branch: main
    autoDeploy: false
    envVars:
        - key: PYTHON_VERSION
          value: 3.10
        - key: WEB_CONCURRENCY
          value: 4
        - key: DJANGO_SETTINGS_MODULE
          value: cotal_drf_api.settings.prod
        - key: DJANGO_SECRET_KEY
          generateValue: true
        - key: DJANGO_CLOUDINARY_URL
          generateValue: true
        - key: DJANGO_ADMIN_URL
          generateValue: true
        - key: DATABASE_URL
          fromDatabase:
            name: cotal-api
            property: connectionString

databases:
  - name: cotal-api
    region: Frankfurt
    databaseName: cotal
    user: cotal
