databases:
  - name: cotal-db
    databaseName: cotal-api-db

services: 
  - type: web
    name: cotal-drf
    env: python
    region: Frankfurt
    buildCommand: "./build.sh"
    startCommand: gunicorn mysite.wsgi:application && python manage.py migrate
    repo: https://github.com/MTraveller/cotal-drf.git
    branch: main
    healthCheckPath: /
    autoDeploy: false
    envVars:
        - key: WEB_CONCURRENCY
          value: 4
        - key: DATABASE_URL
          fromDatabase:
            name: cotal-drf-db
            property: connectionString
        - key: DJANGO_SECRET_KEY
          generateValue: true
        - key: DJANGO_ADMIN_URL
          generateValue: true
        - key: DJANGO_SETTINGS_MODULE
          value: config.settings.production

