
services: 
  - type: web
    name: cotal-api # The subdomain of the url app-name.onrender.com
    env: python
    region: Frankfurt # Change the location to one of the available locations on render.com
    buildCommand: "./build.sh"
    startCommand: gunicorn cotal_drf_api.wsgi
    repo: https://github.com/MTraveller/cotal-drf.git
    branch: main
    autoDeploy: false
    envVars:
        - key: PYTHON_VERSION
          value: 3.10.7 # Choose any python version from 3.7 and up
        - key: WEB_CONCURRENCY
          value: 4 # Number of webworkers
        - key: DJANGO_SETTINGS_MODULE
          value: cotal_drf_api.settings.prod # Change this to current project
        - key: DJANGO_SECRET_KEY
          generateValue: true
        - key: DJANGO_CLOUDINARY_URL
          value: cloudinary:// # Add the remaining secret key
        - key: DJANGO_ALLOWED_HOSTS
          value: .onrender.com # Must change host to full url e.g. app-name.render.com without http
        - key: DATABASE_URL
          fromDatabase:
            name: cotal-api # Change to the below database alias
            property: connectionString
        - key: API_ENDPOINT
          value: insert endpoint value # Change this value on render after deploy then re-deploy

databases:
  - name: cotal-api # Alias inside render !not database name
    region: Frankfurt # Should be in the same location as the web service
    databaseName: cotal # Database name
    user: cotal
