##################################################
# Open .env file in config folder before DEPLOY! #
##################################################
services: 
  - type: web
    name: cotal-api # The subdomain of the url app-name.onrender.com
    env: python
    region: Frankfurt # Change the region to one of the available regions on render.com
    buildCommand: "./build.sh"
    startCommand: gunicorn cotal_drf_api.wsgi # Change only if you know what you're doing!
    repo: https://github.com/MTraveller/cotal-drf.git # Change the repo to your repo
    branch: main
    autoDeploy: false
    envVars:
        - key: PYTHON_VERSION
          value: 3.10.7 # Choose any python version from 3.7 and up
        - key: WEB_CONCURRENCY
          value: 4 # Number of webworkers
        - key: DJANGO_SETTINGS_MODULE
          value: cotal_drf_api.settings.prod # Change only if you know what you're doing!
        - key: DJANGO_SECRET_KEY
          generateValue: true
        - fromGroup: Cotal # Change this to the created environment group on render.com - created in step 3 under Production
        - key: DATABASE_URL
          fromDatabase:
            name: cotal-api-db # Change to the below database alias
            property: connectionString

databases:
  - name: cotal-api-db # Alias inside render !not database name
    region: Frankfurt # Should be in the same location as the web service
    databaseName: cotal # Database name
    user: cotal # Database user
