
services: 
  - type: web
    name: cotal-api
    env: python
    region: Frankfurt
    buildCommand: "true"
    startCommand: gunicorn cotal_drf_api.wsgi:application
    repo: https://github.com/MTraveller/cotal-drf.git
    branch: main
    healthCheckPath: /
    autoDeploy: false
    envVars:
        - key: WEB_CONCURRENCY
          value: 4
        - key: DATABASE_URL
          fromDatabase:
            name: cotal-api
            property: connectionString
        - key: DJANGO_SECRET_KEY
          generateValue: true
        - key: DJANGO_ADMIN_URL
          generateValue: true
        - key: DJANGO_SETTINGS_MODULE
          value: config.settings.production
    startCommand: python manage.py migrate

databases:
  - name: cotal-api
    databaseName: cotal
    user: cotal
