# Generated by Django 4.1.1 on 2022-10-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(blank=True, choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Snapchat', 'Snapchat'), ('TikTok', 'TikTok'), (
                'Telegram', 'Telegram'), ('Dribble', 'Dribble'), ('Pinterest', 'Pinterest'), ('Reddit', 'Reddit'), ('SoundCloud', 'SoundCloud'), ('DeviantArt', 'DeviantArt')], max_length=10, null=True),
        ),
    ]
