# Generated by Django 4.1.2 on 2022-10-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_award_certificate_creative_linktree_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='title',
            field=models.CharField(default='Profile Activity', max_length=16),
        ),
        migrations.AlterField(
            model_name='setting',
            name='activity',
            field=models.CharField(choices=[('1', 'Show'), ('0', 'Hide')], default='1', max_length=1),
        ),
    ]
