# Generated by Django 4.1.1 on 2022-10-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_link_link_alter_link_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[(None, 'Not Specified'), ('Employee', 'Employee'), ('Job Seeker', 'Job Seeker'), ('Open To Collaborate', 'Open To Collaborate'), ('Owner', 'Owner')], default='Not Specified', max_length=19, null=True),
        ),
    ]
