# Generated by Django 4.1.2 on 2022-10-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_link_link_setting_portfolio_creative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
