# Generated by Django 4.1.2 on 2022-10-06 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_link_link_setting_portfolio_creative_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='Linktree',
        ),
        migrations.RemoveField(
            model_name='Linktree',
            name='link',
        ),
        migrations.AddField(
            model_name='linktree',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='linktree',
            name='title',
            field=models.CharField(default='Linktree', max_length=8),
        ),
        migrations.AlterField(
            model_name='Linktree',
            name='profile',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='linktree', to='core.profile'),
        ),
    ]
