# Generated by Django 4.1.2 on 2022-10-12 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_by_name', models.CharField(max_length=300)),
                ('followed_by_username', models.CharField(max_length=150)),
                ('following_by_name', models.CharField(max_length=300)),
                ('following_by_username', models.CharField(max_length=150)),
                ('follower_choice', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=1)),
                ('followed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='profiles.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='profiles.profile')),
            ],
        ),
    ]
