# Generated by Django 4.1.1 on 2022-10-01 11:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import userprofile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external', models.CharField(max_length=200, validators=[django.core.validators.URLValidator])),
                ('social', models.CharField(choices=[(None, '(Unknown)'), ('IG', 'Instagram'), ('FB', 'Facebook'), ('TW', 'Twitter'), ('SP', 'Snapchat'), ('TT', 'TikTok'), ('TG', 'Telegram'), ('DB', 'Dribble'), ('PT', 'Pinterest'), ('RD', 'Reddit'), ('SC', 'SoundCloud'), ('DA', 'DeviantArt')], default='(Unknown)', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=userprofile.models.user_directory_path)),
                ('status', models.CharField(choices=[(None, '(Unknown)'), ('EP', 'Employee'), ('JS', 'Job Seeker'), ('OC', 'Open To Collaborate'), ('OW', 'Owner')], default='(Unknown)', max_length=2)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.profilelink')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
